# Generated by Django 4.0.5 on 2022-06-07 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Roster', '0003_roster_end_time_roster_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='roster',
            name='guild',
            field=models.CharField(default='', max_length=200),
        ),
    ]
