# Generated by Django 4.0.5 on 2022-06-07 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Roster', '0004_roster_guild'),
    ]

    operations = [
        migrations.AddField(
            model_name='roster',
            name='faction',
            field=models.CharField(choices=[('Agility and Strength', 'Agil And Str'), ('Armor Percent', 'Armor Perc'), ('Attack Power', 'Atck Pow'), ('Attack Power Percent', 'Atck Pow Perc'), ('Heroism', 'Hero'), ('Damage Percent', 'Damage Perc'), ('Damage Reduction Percent', 'Damage Reduct Perc'), ('Haste Percent', 'Haste Perc'), ('Healing Recieved Percent', 'Healing Rec Perc'), ('Heath', 'Health'), ('Intellect', 'Int'), ('Mana Per Second', 'Mana Per'), ('Melee Critical Percent', 'Mele Crit Perc'), ('Melee Haste Percent', 'Mele Haste Perc'), ('Replenishment', 'Replinish')], default='Both', max_length=200),
        ),
    ]
