# Generated by Django 4.0.5 on 2022-06-07 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Roster', '0005_roster_faction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roster',
            name='faction',
            field=models.CharField(choices=[('Alliance', 'Alliance'), ('Horde', 'Horde'), ('Both', 'Both')], default='Both', max_length=200),
        ),
    ]
